# Eithery Lab, 2016.
# UserAccount model specs.

describe UserAccount do
  subject(:user) { FactoryGirl.build :user_account }

  it_behaves_like 'a valid domain model'
  it_behaves_like 'it has timestamps'

  it { should respond_to :login, :email, :email_confirmation }
  it { should respond_to :password, :password_confirmation, :password_digest, :remember_digest }
  it { should respond_to :crew_lead?, :financier?, :gatekeeper?, :admin? }
  it { should respond_to :activation_digest, :activated?, :activated_at }
  it { should respond_to :reset_digest, :reset_sent_at }
  it { should respond_to :crew, :participants }
  it { should respond_to :name }
  it { should respond_to :authenticate }

  it { should have_db_index :crew_id }
  it { should have_db_index(:login).unique }
  it { should have_db_index(:email).unique }
  it { should have_db_index :activation_digest }
  it { should have_db_index :reset_digest }

  it { should validate_presence_of :login }
  it { should validate_presence_of :email }
  it { should validate_presence_of :email_confirmation }

  it { should have_secure_password }
  it { should validate_confirmation_of :email }
  it { should validate_confirmation_of :password }

  it { should validate_length_of(:login).is_at_least(4).is_at_most(255) }
  it { should validate_length_of(:password).is_at_least(6).is_at_most(72) }

  it { should validate_uniqueness_of(:login).case_insensitive }
  it { should validate_uniqueness_of(:email).case_insensitive }

  it { should belong_to :crew }
  it { should have_many(:participants).dependent :destroy }


  describe 'validation' do
    context 'when email has an invalid format' do
      it 'is expected to not be valid' do
        %w[user@foo,com user_at_foo.org example.user@foo.foo@bar_baz.com foo_bar+baz.com].each do |invalid_email|
          user.email = user.email_confirmation = invalid_email
          expect(user).to_not be_valid
          expect(user).to have(1).error_on(:email)
        end
      end
    end

    context 'when email has a valid format' do
      it 'is expected to be valid' do
        %w[user@foo.COM A_US-ER@f.b.org first.last@foo.jp a+b@baz.cn].each do |valid_email|
          user.email = user.email_confirmation = valid_email
          expect(user).to be_valid
          expect(user).to have(:no).errors
        end
      end
    end
  end


  context 'when just created' do
    subject { UserAccount.new }

    it { is_expected.to_not be_valid }
    it { is_expected.to_not be_activated }
    it { is_expected.to_not be_a_crew_lead }
    it { is_expected.to_not be_a_financier }
    it { is_expected.to_not be_a_gatekeeper }
    it { is_expected.to_not be_an_admin }
  end
end

=begin
    context "when email" do
      describe "address with mixed case" do
        let(:mixed_case_email) { "Foo@ExAPMle.CoM" }
        it "should be saved as all lower case" do
          user.email = user.email_confirmation = mixed_case_email
          user.save
          user.reload.email.should == mixed_case_email.downcase
        end
      end
    end

  Password validation check.

  describe "#authenticate" do
    before { user.save }
    let(:found_user_account) { UserAccount.find_by_email(user.email) }

    context "with valid password" do
      it { should == found_user_account.authenticate(user.password) }
    end

    context "with invalid password" do
      let(:user_account_for_invalid_password) { found_user_account.authenticate('invalid') }
      it { should_not == user_account_for_invalid_password }
      specify { user_account_for_invalid_password.should be false }
    end
  end


  describe "#name" do
    specify { user.name.should == user.login }
  end


  describe "#participants" do
    subject { gwen.user_account }
    before { gwen; maryika; gaby; }

    it { should have(3).participants }
    its(:participants) { should include(gwen, maryika, gaby) }
    specify { empty_user_account.should_not have(:any).participants }
  end


  describe "#crew" do
    it "blank for the newly created user" do
      user = new_user
      user.save
      user.reload.crew.should be_blank
    end

    it "equals to the crew this user belongs to" do
      fix_crew = FactoryGirl.create(:fix_crew)
      fix = FactoryGirl.create(:active_user, crew: fix_crew)
      fix.crew.should be_equal(fix_crew)
    end
  end


  describe "#remember_token" do
    it "generated by save user account" do
      user = new_user
      user.remember_token.should be_blank
      user.save
      user.remember_token.should_not be_blank
      user.reload.remember_token.should_not be_blank
    end

    it "different from previous one after save operations" do
      token_before = gwen.user_account.remember_token
      token_before.should_not be_blank
      gwen.user_account.save
      gwen.user_account.remember_token.should_not == token_before
    end
  end


  describe "#activate" do
    context "wnen provided activation code or token is invalid" do
      let(:invalid_code_or_token) { '123456789' }
      before { user.activate(invalid_code_or_token) }

      it { should_not be_active }
      its(:activated_at) { should be_nil }
    end

    context "by valid code" do
      before { user.activate(user.activation_code) }
      it { should be_active }
      its(:activated_at) { should_not be_nil }
    end

    context "by valid activation token" do
      before { user.activate(user.activation_token) }
      it { should be_active }
      its(:activated_at) { should_not be_nil }
    end
  end


  describe "#activation_token" do
    subject { new_user.activation_token }

    context "for new user account" do
      it { should be_blank }
    end

    context "for saved user account" do
      before { new_user.save }
      it { should_not be_blank }
    end
  end


  describe "#activation_code" do
    subject { new_user.activation_code }

    context "for new user account" do
      it { should be_blank }
    end

    context "for saved user account" do
      before { new_user.save }

      it { should_not be_blank }
      it { should have_at_least(6).digits }
    end
  end


  describe "#generate_reset_token" do
    subject { gwen.user_account }
    before { gwen.user_account.generate_reset_token }

    its(:reset_password_token) { should_not be_blank }
    its(:reset_password_expired_at) { should_not be_blank }
  end


  describe "#reset" do
    subject { gwen.user_account }
    before do
      gwen.user_account.generate_reset_token
      gwen.user_account.reset
    end

    its(:reset_password_token) { should be_nil }
    its(:reset_password_expired_at) { should be_nil }
  end
end
=end