development:
  adapter: postgresql
  encoding: unicode
  database: blue_trolley_dev
  pool: 5
  username: admin
  password: admin


test:
  adapter: postgresql
  encoding: unicode
  database: blue_trolley_test
  pool: 5
  username: admin
  password: admin


production:
  adapter: postgresql
  encoding: unicode
  database: blue_trolley
  pool: 5
  username: admin
  password: admin
