development:
  adapter: sqlite3
  database: db/blue_trolley.sqlite3
  pool: 5
  timeout: 5000

# SQL server settings:
# adapter: sqlserver
# dataserver: localhost\SQL2012
# database: blue_trolley
# username: rails
# password: blue_troll


test: &test
  adapter: sqlite3
  database: db/blue_trolley_test.sqlite3
  pool: 5
  timeout: 5000


production:
  adapter: sqlite3
  database: db/blue_trolley.sqlite3
  pool: 5
  timeout: 5000


cucumber:
  <<: *test
