default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/blue_trolley_dev.sqlite3

test:
  <<: *default
  database: db/blue_trolley_test.sqlite3


production:
  adapter: postgresql
  encoding: unicode
  database: blue_trolley
  pool: 5
  username: admin
  password: admin
